/*
 * This source file was generated by the Gradle 'init' task
 */
package org.epj;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        // Action classUnderTest = new Action();
        // assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should
        // return 'true'");
    }
}
